[package]
name = "bmemcached"
version = "0.1.0"
authors = ["Jayson Reis <santosdosreis@gmail.com>"]

[dependencies]
byteorder = "0.5.1"
conhash = "0.3.2"
enum_primitive = "0.1.0"
log = "*"
num = "0.1.31"

[dev-dependencies]
env_logger = "*"
